baseURL = "https://acarres.github.io/ddd-fastapi-rentals/"
languageCode = "es-es"
title = "Blog de acarres"
theme = "PaperMod"

[[menu.main]]
name = "Curso DDD con FastAPI"
url = "/curso-ddd-fastapi/"
weight = 1

[params]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  mainSections = ["posts", "curso-ddd-fastapi"]